config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "lists#index"
  resources :lists, only: [ :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # dependent: :restrict_with_error
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      puts @bookmark.errors.full_messages
      render :new
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list), notice: 'Bookmark was successfully deleted.'
  end
  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
    # @movie = Movie.find(params[:id])
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list), notice: "List was successfully created."
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Add a bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.error_notification %>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<nav class="navbar sticky-top navbar-light bg-white justify-content-center">
  <div class="container m-0 p-0">
    <div>
    <a class="navbar-brand" href="#">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFl1uRphOHe0ssyZoZq-YV-PohQbh9EkmNpA&s" alt="" width="40" height="40">
    </a>
    </div>
    <div>
      <%= link_to "My lists", root_path, class: "text-decoration-none text-black p-3" %>
      <%= link_to "New list", new_list_path, class: "text-decoration-none text-black p-3" %>
    </div>
  </div>
</nav>

<div class="banner">
  <div class="container">
    <h1>Save any kind of movies</h1>
    <h2><%=@lists.sample.name%></h2>
  </div>
</div>

<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-8">
      <h3 class="text-black text-start">My lists</h3>
        <div class="card-list d-flex justify-content-start mt-3">
          <% @lists.each do |list| %>
            <% if list.photo.attached? %>
              <div class="card-item me-5 position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(list.photo.key) %>'); background-size: cover; background-position: center;">
                <%= link_to list.name, list_path(list), class: "text-decoration-none text-white position-absolute top-50 start-50 translate-middle" %>
              </div>
            <% else %>
              <div class="card-item me-5 position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)); background-size: cover; background-position: center;">
                <%= link_to list.name, list_path(list), class: "text-decoration-none text-white position-absolute top-50 start-50 translate-middle" %>
              </div>
            <% end %>
          <% end %>
        </div>
    </div>


    <div class="col-4">
      <%= link_to "Add a new list", new_list_path, class: "btn btn-primary" %>
    </div>

  </div>
</div>

app/views/lists/new.html.erb
<h1>Add a list</h1>
<%= simple_form_for(@list) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <div class="banner-list" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path(@list.photo.key, crop: :fill) %>')">
      <h1><%= @list.name %></h1>
  </div>
  <div class="mt-5">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="container border text-black p-5">
        <%= bookmark.comment%>
      </div>
      <%= link_to "Delete a bookmark", list_bookmark_path(@list, bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <% end %>
    <%= link_to "Add a bookmark", new_list_bookmark_path(@list) %>
  </div>
      <div class="btn btn-primary">
        <%= link_to "Delete this list", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"text-decoration-none text-white"%>
      </div>
</div>